[book]
title = "Rust异步编程"
authors = ["Taylor Cramer"]

[build]
create-missing = false

[preprocess.links]

[output.html]
git-repository-url = "https://github.com/cinea4678/async-book"
site-url = "/async-book/"

[output.linkcheck]
follow-web-links = true
traverse-parent-directories = false
